networks:
  default:
    driver: bridge
    name: roboshop
    #external: true # already created network using docker network create roboshop cmd
services:
  mongodb:
    image: dnavarma/mongodb:v1
    container_name: mongodb
  catalogue:
    image: dnavarma/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: dnavarma/user:v1
    container_name: user
    depends_on:
      - redis
      - mongodb
  cart:
    image: dnavarma/cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
  mysql:
    image: dnavarma/mysql:v1
    container_name: mysql
  shipping:
    image: dnavarma/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
